//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;

    public partial class Beer
    {
        public int BeerID { get; set; }
        public string Name { get; set; }
        public string Brewery { get; set; }
        public string Country { get; set; }
        public Nullable<double> Degree { get; set; }
        public string Color { get; set; }
        public string Fermentation { get; set; }
        public string SpecialCat { get; set; }
    }
}
